/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;
import controle.ContatoCTL;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelos.Contato;
import modelos.Telefone;
import javax.swing.table.DefaultTableModel;
import modelos.IcrudContato;

/**
 *
 * @author eugen
 */
public class TelaPrincipal extends javax.swing.JFrame {
    //Atributo da Controle
    IcrudContato objContatoCTL = new ContatoCTL();
    private Integer idEmEdicao = null;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
      initComponents();
      this.setLocationRelativeTo(null);
      try {
        javax.swing.text.MaskFormatter mf =
            new javax.swing.text.MaskFormatter("+## (##) #####-####");
        mf.setPlaceholderCharacter('_');
        jFormattedTextFieldTelefone.setFormatterFactory(
            new javax.swing.text.DefaultFormatterFactory(mf)
        );
    } catch (java.text.ParseException ex) {
        ex.printStackTrace();
    }
    try {
        mostrarListaDeContatos();
    } catch (Exception erro) {
        JOptionPane.showMessageDialog(rootPane, erro.getMessage());
    }
    }
    private void mostrarListaDeContatos() throws Exception{
      try {
        ArrayList<Contato> listaDeContatos = objContatoCTL.listagemDeContatos();
        DefaultTableModel model =  (DefaultTableModel) jTableDadosDosContatos.getModel();
        model.setNumRows(0);
        if(listaDeContatos.isEmpty()) return;
        for (Contato pessoa : listaDeContatos) {
            String[] linha = new String[4];
            linha[0] = pessoa.getIdContato() + "";
            linha[1] = pessoa.getNomeCompleto();
            linha[2] = pessoa.getEmail();

            String telefoneStr = "";
            if (pessoa.getTelefone() != null) {
                telefoneStr = pessoa.getTelefone().toString();
            }
            linha[3] = telefoneStr;

            model.addRow(linha);
        }
      } catch (Exception erro) {
        throw erro;
      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelDosDados = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldIdContato = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jPanelAcoes = new javax.swing.JPanel();
        jButtonIncluir = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonConsultar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextFieldTelefone = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDadosDosContatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA DE CONTROLE DA AGENDA DE CONTATOS");

        jPanelPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        jPanelPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AGENDA DE CONTATOS");

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanelDosDados.setBackground(new java.awt.Color(0, 0, 153));

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NOME");

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("IDENTIFICADOR");

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("E-MAIL");

        jTextFieldIdContato.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jTextFieldIdContato.setForeground(new java.awt.Color(0, 0, 153));

        jTextFieldEmail.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jTextFieldEmail.setForeground(new java.awt.Color(0, 0, 153));

        jTextFieldNome.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jTextFieldNome.setForeground(new java.awt.Color(0, 0, 153));

        jPanelAcoes.setBackground(new java.awt.Color(102, 102, 102));

        jButtonIncluir.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jButtonIncluir.setForeground(new java.awt.Color(0, 0, 102));
        jButtonIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/icones/iconeA_16.png"))); // NOI18N
        jButtonIncluir.setText("INCLUIR");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        jButtonExcluir.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jButtonExcluir.setForeground(new java.awt.Color(0, 0, 102));
        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/icones/excluir16.png"))); // NOI18N
        jButtonExcluir.setText("EXCLUIR");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonConsultar.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jButtonConsultar.setForeground(new java.awt.Color(0, 0, 102));
        jButtonConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/icones/buscar16.png"))); // NOI18N
        jButtonConsultar.setText("CONSULTAR");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });

        jButtonAlterar.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jButtonAlterar.setForeground(new java.awt.Color(0, 0, 102));
        jButtonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/icones/iconeC_16.png"))); // NOI18N
        jButtonAlterar.setText("ALTERAR");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAcoesLayout = new javax.swing.GroupLayout(jPanelAcoes);
        jPanelAcoes.setLayout(jPanelAcoesLayout);
        jPanelAcoesLayout.setHorizontalGroup(
            jPanelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAcoesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanelAcoesLayout.setVerticalGroup(
            jPanelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAcoesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButtonIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jButtonExcluir)
                .addGap(15, 15, 15))
        );

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TELEFONE");

        jFormattedTextFieldTelefone.setForeground(new java.awt.Color(0, 0, 153));
        jFormattedTextFieldTelefone.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N

        javax.swing.GroupLayout jPanelDosDadosLayout = new javax.swing.GroupLayout(jPanelDosDados);
        jPanelDosDados.setLayout(jPanelDosDadosLayout);
        jPanelDosDadosLayout.setHorizontalGroup(
            jPanelDosDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDosDadosLayout.createSequentialGroup()
                .addGroup(jPanelDosDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDosDadosLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanelDosDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelDosDadosLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEmail))
                            .addGroup(jPanelDosDadosLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDosDadosLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelDosDadosLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIdContato, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jPanelAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );
        jPanelDosDadosLayout.setVerticalGroup(
            jPanelDosDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDosDadosLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanelDosDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelDosDadosLayout.createSequentialGroup()
                        .addGroup(jPanelDosDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIdContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelDosDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelDosDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDosDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTableDadosDosContatos.setBackground(new java.awt.Color(0, 0, 0));
        jTableDadosDosContatos.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jTableDadosDosContatos.setForeground(new java.awt.Color(102, 153, 255));
        jTableDadosDosContatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDENTIFICADOR", "NOME COMPLETO", "E-MAIL", "TELEFONE"
            }
        ));
        jScrollPane1.setViewportView(jTableDadosDosContatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelDosDados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDosDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void limparDadosTela(){
    jTextFieldIdContato.setText("");
    jTextFieldNome.setText("");
    jTextFieldEmail.setText("");
    jFormattedTextFieldTelefone.setValue(null);
    idEmEdicao = null;
  }
  private boolean emailValido(String email) {
    if (email == null) return false;
    email = email.trim();
    if (email.isEmpty()) return false;

    int posArroba = email.indexOf('@');
    int posPonto  = email.lastIndexOf('.');

    if (posArroba <= 0) return false;
    if (posPonto <= posArroba + 1) return false;
    if (posPonto == email.length() - 1) return false;

    return true;
  }
  private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
    // TODO add your handling code here:
     try {
        int idContato = Integer.parseInt(jTextFieldIdContato.getText().trim());
        String nome = jTextFieldNome.getText().trim();
        String email = jTextFieldEmail.getText().trim();
        String telefoneTexto = jFormattedTextFieldTelefone.getText();

        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o nome.");
            return;
        }
        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o e-mail.");
            return;
        }
        if (!emailValido(email)) {
            JOptionPane.showMessageDialog(this, "E-mail inválido.");
            return;
        }

        Telefone telefone = Telefone.fromFormattedString(telefoneTexto);
        if (telefone == null) {
            JOptionPane.showMessageDialog(this, "Informe o telefone.");
            return;
        }

        Contato objetoContato = new Contato(idContato, nome, email, telefone);
        objContatoCTL.incluir(objetoContato);

        limparDadosTela();
        mostrarListaDeContatos();
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Identificador deve ser um número inteiro.");
    } catch (Exception erro) {
        JOptionPane.showMessageDialog(this, erro.getMessage());
    }
  }//GEN-LAST:event_jButtonIncluirActionPerformed

  private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
    // TODO add your handling code here:
    try {
        Contato c = null;

        String txtId = jTextFieldIdContato.getText().trim();
        String nome = jTextFieldNome.getText().trim();

        if (!txtId.isEmpty()) {
            int id = Integer.parseInt(txtId);
            c = objContatoCTL.buscarID(id);
        } else if (!nome.isEmpty()) {
            c = objContatoCTL.consultar(nome);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Informe o identificador OU o nome para consultar.");
            return;
        }

        if (c == null) {
            JOptionPane.showMessageDialog(this, "Contato não encontrado.");
            return;
        }

        idEmEdicao = c.getIdContato();

        jTextFieldIdContato.setText(String.valueOf(c.getIdContato()));
        jTextFieldNome.setText(c.getNomeCompleto());
        jTextFieldEmail.setText(c.getEmail());
        if (c.getTelefone() != null) {
            jFormattedTextFieldTelefone.setText(c.getTelefone().toString());
        } else {
            jFormattedTextFieldTelefone.setValue(null);
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Identificador deve ser um número inteiro.");
    } catch (Exception erro) {
        JOptionPane.showMessageDialog(this, erro.getMessage());
    }
    
  }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        // TODO add your handling code here:
        try {
            if (idEmEdicao == null) {
                JOptionPane.showMessageDialog(this,
                        "Consulte um contato antes de alterar.");
                return;
            }

            String txtIdCampo = jTextFieldIdContato.getText().trim();
            if (!txtIdCampo.equals(String.valueOf(idEmEdicao))) {
                JOptionPane.showMessageDialog(this,
                        "Não é permitido alterar o identificador.\n" +
                        "O ID será restaurado.");
                jTextFieldIdContato.setText(String.valueOf(idEmEdicao));
                return;
            }

            String nome = jTextFieldNome.getText().trim();
            String email = jTextFieldEmail.getText().trim();
            String telefoneTexto = jFormattedTextFieldTelefone.getText();

            if (nome.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Informe o nome.");
                return;
            }
            if (email.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Informe o e-mail.");
                return;
            }
            if (!emailValido(email)) {
                JOptionPane.showMessageDialog(this, "E-mail inválido.");
                return;
            }

            Telefone telefone = Telefone.fromFormattedString(telefoneTexto);
            if (telefone == null) {
                JOptionPane.showMessageDialog(this, "Informe o telefone.");
                return;
            }

            Contato objetoContato = new Contato(idEmEdicao, nome, email, telefone);
            objContatoCTL.alterar(objetoContato);

            limparDadosTela();
            mostrarListaDeContatos();
            JOptionPane.showMessageDialog(this, "Contato alterado com sucesso.");
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        try {
            String txtId = jTextFieldIdContato.getText().trim();
            if (txtId.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Informe o identificador para excluir.");
                return;
            }

            int id = Integer.parseInt(txtId);

            int opcao = JOptionPane.showConfirmDialog(this,
                    "Deseja realmente excluir o contato " + id + "?",
                    "Confirmação", JOptionPane.YES_NO_OPTION);
            if (opcao != JOptionPane.YES_OPTION) {
                return;
            }

            objContatoCTL.excluir(id);

            limparDadosTela();
            mostrarListaDeContatos();
            JOptionPane.showMessageDialog(this, "Contato excluído com sucesso.");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Identificador deve ser um número inteiro.");
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelAcoes;
    private javax.swing.JPanel jPanelDosDados;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDadosDosContatos;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldIdContato;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
